[package]
name = "test-request"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]]
name = "test-request"
path = "main.rs"

[dependencies]
reqwest = { version = "0.12", features = ["blocking"] }
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
hex = "0.4"
